# fly.toml app configuration file generated for waifuverse on 2023-06-30T16:04:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "waifuverse"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
